# Generated by Django 3.1.1 on 2020-09-30 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20200930_1631'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='enquiry',
        ),
    ]
