# Generated by Django 3.1.1 on 2020-09-30 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='course',
        ),
        migrations.CreateModel(
            name='section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.courses')),
            ],
        ),
        migrations.AddField(
            model_name='lessons',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.section'),
        ),
    ]
