# Generated by Django 3.1.1 on 2020-09-30 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20200930_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.courses'),
        ),
    ]
