# Generated by Django 3.1.1 on 2020-09-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_lessons_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='fees',
            field=models.IntegerField(null=True),
        ),
    ]
