# Generated by Django 3.1.1 on 2020-09-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_courses_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='tool',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
