# Generated by Django 3.1.1 on 2020-09-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_courses_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='tool',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
