# Generated by Django 3.1.1 on 2020-09-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_auto_20200930_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='obj',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
