# Generated by Django 3.1.1 on 2020-10-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_courses_trend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
